### ISSUE TITLE
better explain the bias in the game

### ISSUE THREAD

**Issue by jihjihk** [survivalofthebestfit/survivalofthebestfit#15]
1. Bias too vague at times
Feedback: "The idea of "bias" is also sometimes too vague, and imo it works better when you tie it to "being a blueville" resident, so putting more emphasis on "practical" discrimination would bring it home for some people."

2. Narrative: explain why bias happens even if you're intentionally unbiased

several people asked about this: we either leave it as "its hardcoded bc this is an educational experience" or explain that theres a larger & more historic dataset at hand and clarify that part of the story better.
--

**Comment by gaborcsapo** [comment]
+ never forget to focus on the people, instead of machines. Some people got the idea, we are blaming the technology. Maybe we should say a few positive things about ML as well

**Comment by gaborcsapo** [comment]
did my best to improve the text, data and the stats inspector
