### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by jihjihk** [survivalofthebestfit/survivalofthebestfit#5]
some options depending on how formal/community sourced we want this to be
* github wiki
* landing

**Comment by jihjihk** [comment]
@AliaElKattan @mklasinc @gaborcsapo if you guys have past q&a with your friends, feel free to dump them here :)

**Comment by gaborcsapo** [comment]
tried to answer a few faqs in the wrap-up. I think that's where it should be done
